spring.application.name=wallet
spring.profiles.active=dev

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true

# SERVER
server.port=8080
server.servlet.context-path=/wallet
server.servlet.session.timeout=30m

# ENCODING
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true

# FILE UPLOAD
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ERROR
server.error.path=/error

# OTP
OTP.IN.MINS=2

#mail.smtp.auth=true
#mail.smtp.starttls.enable=true
#mail.smtp.host=smtp.zoho.in
#mail.smtp.ssl.trust=smtp.zoho.in
#mail.smtp.port=587
#mail.username=biswajit.behera@aashdit.com
#mail.password=X8tCAkD8y8kg
#body.type=HTML

ALLOWED_HOSTS=139.59.12.212:8080, localhost:3031, localhost:3032, 192.168.3.194:3031, 192.168.3.187:3031, 192.168.3.194:3031,

# MAIL CONFIG
spring.mail.host=smtp.zoho.in
spring.mail.port=587
spring.mail.username=soumya.mohanty@aashdit.com
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.zoho.in

# HIKARI POOL
spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000