#HOME DATABASE
#spring.datasource.url=jdbc:postgresql://localhost:5432/finSecure_wallet
#spring.datasource.username=postgres
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

# OFFICE DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/finSecure_wallet_office
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver