# DATABASE
spring.datasource.url=jdbc:postgresql://localhost:5432/finSecure_wallet
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver